CREATE TABLE restaurant_settings (
    id BIGINT PRIMARY KEY,
    business_name VARCHAR(120) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    timezone VARCHAR(60) NOT NULL,
    primary_color VARCHAR(7) NOT NULL,
    secondary_color VARCHAR(7) NOT NULL,
    phone VARCHAR(30),
    address VARCHAR(250),
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_restaurant_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_restaurant_settings_currency CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_restaurant_settings_primary_color CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_restaurant_settings_secondary_color CHECK (secondary_color ~ '^#[0-9A-Fa-f]{6}$')
);

INSERT INTO restaurant_settings (
    id,
    business_name,
    display_name,
    currency_code,
    timezone,
    primary_color,
    secondary_color
) VALUES (
    1,
    'Mi restaurante',
    'Mi restaurante',
    'MXN',
    'America/Mazatlan',
    '#2563EB',
    '#111827'
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(250),
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_categories_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_categories_name_ci ON categories (LOWER(name));
CREATE INDEX idx_categories_active_sort ON categories (active, sort_order, name);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories (id),
    sku VARCHAR(40),
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    price NUMERIC(12, 2) NOT NULL,
    destination VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_destination CHECK (destination IN ('KITCHEN', 'BAR', 'NONE'))
);

CREATE UNIQUE INDEX uk_products_sku_ci
    ON products (LOWER(sku))
    WHERE sku IS NOT NULL;
CREATE INDEX idx_products_category_name ON products (category_id, name);
CREATE INDEX idx_products_operation ON products (active, available, destination);
