ALTER TABLE restaurant_settings RENAME TO business_settings;
ALTER TABLE business_settings
    RENAME CONSTRAINT restaurant_settings_pkey TO business_settings_pkey;
ALTER TABLE business_settings
    RENAME CONSTRAINT ck_restaurant_settings_singleton TO ck_business_settings_singleton;
ALTER TABLE business_settings
    RENAME CONSTRAINT ck_restaurant_settings_currency TO ck_business_settings_currency;
ALTER TABLE business_settings
    RENAME CONSTRAINT ck_restaurant_settings_primary_color TO ck_business_settings_primary_color;
ALTER TABLE business_settings
    RENAME CONSTRAINT ck_restaurant_settings_secondary_color TO ck_business_settings_secondary_color;

ALTER TABLE business_settings
    ADD COLUMN business_type VARCHAR(30) NOT NULL DEFAULT 'OTHER';
ALTER TABLE business_settings
    ADD CONSTRAINT ck_business_settings_type
        CHECK (business_type IN ('RESTAURANT', 'RETAIL', 'SERVICES', 'OTHER'));

UPDATE business_settings
SET business_name = 'Essential',
    display_name = 'Essential',
    primary_color = '#31D6A0',
    secondary_color = '#111827'
WHERE business_name = 'Mi restaurante'
  AND display_name = 'Mi restaurante';

ALTER TABLE products DROP CONSTRAINT ck_products_destination;
UPDATE products SET destination = 'PRODUCTION' WHERE destination = 'KITCHEN';
UPDATE products SET destination = 'SERVICE' WHERE destination = 'BAR';
ALTER TABLE products
    ADD CONSTRAINT ck_products_destination
        CHECK (destination IN ('PRODUCTION', 'SERVICE', 'NONE'));

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    role VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_users_role
        CHECK (role IN ('OWNER', 'ADMIN', 'MANAGER', 'CASHIER', 'OPERATOR'))
);

CREATE UNIQUE INDEX uk_app_users_username_ci ON app_users (LOWER(username));
CREATE INDEX idx_app_users_active_role ON app_users (active, role);
