CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(120) NOT NULL,
    address VARCHAR(250),
    phone VARCHAR(30),
    timezone VARCHAR(60) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_branches_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_branches_code_ci ON branches (LOWER(code));
CREATE INDEX idx_branches_active_sort ON branches (active, sort_order, name);

CREATE TABLE operational_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches (id),
    name VARCHAR(120) NOT NULL,
    description VARCHAR(250),
    area_type VARCHAR(30) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_operational_areas_type
        CHECK (area_type IN ('SERVICE', 'PRODUCTION', 'STORAGE', 'CHECKOUT', 'OFFICE', 'OTHER')),
    CONSTRAINT ck_operational_areas_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_operational_areas_branch_name_ci
    ON operational_areas (branch_id, LOWER(name));
CREATE INDEX idx_operational_areas_branch_sort
    ON operational_areas (branch_id, active, sort_order, name);

CREATE TABLE service_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id BIGINT NOT NULL REFERENCES operational_areas (id),
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(250),
    point_type VARCHAR(30) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_service_points_type
        CHECK (point_type IN ('TABLE', 'COUNTER', 'CHECKOUT', 'STATION', 'ROOM', 'DESK', 'WINDOW', 'OTHER')),
    CONSTRAINT ck_service_points_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_service_points_area_code_ci
    ON service_points (area_id, LOWER(code));
CREATE INDEX idx_service_points_area_sort
    ON service_points (area_id, active, sort_order, name);

CREATE TABLE branch_user_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_branch_user_assignments UNIQUE (branch_id, user_id)
);

CREATE INDEX idx_branch_user_assignments_user ON branch_user_assignments (user_id, branch_id);

INSERT INTO branches (
    code,
    name,
    address,
    phone,
    timezone,
    sort_order
)
SELECT
    'PRINCIPAL',
    display_name,
    address,
    phone,
    timezone,
    0
FROM business_settings
WHERE id = 1;

INSERT INTO branch_user_assignments (branch_id, user_id)
SELECT branch.id, app_user.id
FROM branches branch
CROSS JOIN app_users app_user
WHERE branch.code = 'PRINCIPAL'
  AND app_user.active = TRUE;
