CREATE TABLE restaurant_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches (id),
    service_point_id BIGINT REFERENCES service_points (id),
    assigned_user_id BIGINT NOT NULL REFERENCES app_users (id),
    opened_by_user_id BIGINT NOT NULL REFERENCES app_users (id),
    service_mode VARCHAR(30) NOT NULL,
    guest_count INTEGER NOT NULL DEFAULT 1,
    customer_reference VARCHAR(120),
    notes VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_restaurant_orders_service_mode
        CHECK (service_mode IN ('DINE_IN', 'TAKEOUT')),
    CONSTRAINT ck_restaurant_orders_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_restaurant_orders_guest_count
        CHECK (guest_count BETWEEN 1 AND 99),
    CONSTRAINT ck_restaurant_orders_service_point
        CHECK (
            (service_mode = 'DINE_IN' AND service_point_id IS NOT NULL)
            OR (service_mode = 'TAKEOUT' AND service_point_id IS NULL)
        ),
    CONSTRAINT ck_restaurant_orders_closed_at
        CHECK (
            (status IN ('OPEN', 'IN_PROGRESS') AND closed_at IS NULL)
            OR (status IN ('COMPLETED', 'CANCELLED') AND closed_at IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uk_restaurant_orders_active_service_point
    ON restaurant_orders (service_point_id)
    WHERE service_point_id IS NOT NULL
      AND status IN ('OPEN', 'IN_PROGRESS');

CREATE INDEX idx_restaurant_orders_branch_status_opened
    ON restaurant_orders (branch_id, status, opened_at DESC);

CREATE INDEX idx_restaurant_orders_assigned_active
    ON restaurant_orders (assigned_user_id, status, opened_at DESC);
