CREATE TABLE product_modifier_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id),
    name VARCHAR(100) NOT NULL,
    min_selections INTEGER NOT NULL DEFAULT 0,
    max_selections INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_modifier_groups_selections
        CHECK (min_selections >= 0 AND max_selections >= 1 AND min_selections <= max_selections),
    CONSTRAINT ck_modifier_groups_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_modifier_groups_product_name_ci
    ON product_modifier_groups (product_id, LOWER(name));
CREATE INDEX idx_modifier_groups_product_active_sort
    ON product_modifier_groups (product_id, active, sort_order, name);

CREATE TABLE product_modifier_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES product_modifier_groups (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    price_delta NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_modifier_options_price_delta CHECK (price_delta >= 0),
    CONSTRAINT ck_modifier_options_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_modifier_options_group_name_ci
    ON product_modifier_options (group_id, LOWER(name));
CREATE INDEX idx_modifier_options_group_active_sort
    ON product_modifier_options (group_id, active, sort_order, name);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES restaurant_orders (id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products (id),
    product_name VARCHAR(120) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    destination VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    notes VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_order_items_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_quantity CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT ck_order_items_destination
        CHECK (destination IN ('PRODUCTION', 'SERVICE', 'NONE'))
);

CREATE INDEX idx_order_items_order_created ON order_items (order_id, created_at, id);

CREATE TABLE order_item_modifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL REFERENCES order_items (id) ON DELETE CASCADE,
    modifier_option_id BIGINT NOT NULL REFERENCES product_modifier_options (id),
    group_name VARCHAR(100) NOT NULL,
    option_name VARCHAR(100) NOT NULL,
    price_delta NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_order_item_modifier UNIQUE (order_item_id, modifier_option_id)
);

CREATE INDEX idx_order_item_modifiers_item ON order_item_modifiers (order_item_id, id);
