ALTER TABLE order_items
    ADD COLUMN sent_at TIMESTAMPTZ;

CREATE INDEX idx_order_items_pending_dispatch
    ON order_items (order_id, destination, created_at)
    WHERE sent_at IS NULL AND destination IN ('PRODUCTION', 'SERVICE');

CREATE TABLE preparation_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES restaurant_orders (id),
    branch_id BIGINT NOT NULL REFERENCES branches (id),
    destination VARCHAR(20) NOT NULL,
    sequence_number INTEGER NOT NULL,
    sent_by_user_id BIGINT NOT NULL REFERENCES app_users (id),
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_preparation_tickets_destination
        CHECK (destination IN ('PRODUCTION', 'SERVICE')),
    CONSTRAINT ck_preparation_tickets_sequence CHECK (sequence_number >= 1),
    CONSTRAINT uk_preparation_tickets_order_destination_sequence
        UNIQUE (order_id, destination, sequence_number)
);

CREATE INDEX idx_preparation_tickets_branch_destination_sent
    ON preparation_tickets (branch_id, destination, sent_at, id);
CREATE INDEX idx_preparation_tickets_order ON preparation_tickets (order_id, sent_at, id);

CREATE TABLE preparation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES preparation_tickets (id) ON DELETE CASCADE,
    order_item_id BIGINT NOT NULL REFERENCES order_items (id),
    product_name VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL,
    notes VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMPTZ,
    ready_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_preparation_items_quantity CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT ck_preparation_items_status
        CHECK (status IN ('PENDING', 'IN_PREPARATION', 'READY', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT uk_preparation_items_order_item UNIQUE (order_item_id)
);

CREATE INDEX idx_preparation_items_ticket_status
    ON preparation_items (ticket_id, status, created_at, id);

CREATE TABLE preparation_item_modifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preparation_item_id BIGINT NOT NULL REFERENCES preparation_items (id) ON DELETE CASCADE,
    group_name VARCHAR(100) NOT NULL,
    option_name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_preparation_item_modifiers_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_preparation_item_modifiers_item
    ON preparation_item_modifiers (preparation_item_id, sort_order, id);
