CREATE TABLE order_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id UUID NOT NULL,
    order_id BIGINT NOT NULL REFERENCES restaurant_orders (id),
    amount NUMERIC(12, 2) NOT NULL,
    tendered_amount NUMERIC(12, 2) NOT NULL,
    method VARCHAR(20) NOT NULL,
    method_label VARCHAR(60),
    reference VARCHAR(120),
    notes VARCHAR(250),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    received_by_user_id BIGINT NOT NULL REFERENCES app_users (id),
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    voided_by_user_id BIGINT REFERENCES app_users (id),
    voided_at TIMESTAMPTZ,
    void_reason VARCHAR(250),
    CONSTRAINT uk_order_payments_operation UNIQUE (operation_id),
    CONSTRAINT ck_order_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_order_payments_tendered CHECK (tendered_amount >= amount),
    CONSTRAINT ck_order_payments_method
        CHECK (method IN ('CASH', 'CARD', 'TRANSFER', 'OTHER')),
    CONSTRAINT ck_order_payments_method_label
        CHECK (
            (method = 'OTHER' AND method_label IS NOT NULL)
            OR (method <> 'OTHER' AND method_label IS NULL)
        ),
    CONSTRAINT ck_order_payments_non_cash_tendered
        CHECK (method = 'CASH' OR tendered_amount = amount),
    CONSTRAINT ck_order_payments_status
        CHECK (status IN ('ACTIVE', 'VOIDED')),
    CONSTRAINT ck_order_payments_void
        CHECK (
            (status = 'ACTIVE'
                AND voided_by_user_id IS NULL
                AND voided_at IS NULL
                AND void_reason IS NULL)
            OR (status = 'VOIDED'
                AND voided_by_user_id IS NOT NULL
                AND voided_at IS NOT NULL
                AND void_reason IS NOT NULL)
        )
);

CREATE INDEX idx_order_payments_order_received
    ON order_payments (order_id, received_at, id);

CREATE INDEX idx_order_payments_order_active
    ON order_payments (order_id, status)
    WHERE status = 'ACTIVE';
