CREATE TABLE cash_register_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches (id),
    opening_amount NUMERIC(12, 2) NOT NULL,
    opening_notes VARCHAR(250),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    opened_by_user_id BIGINT NOT NULL REFERENCES app_users (id),
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_by_user_id BIGINT REFERENCES app_users (id),
    closed_at TIMESTAMPTZ,
    expected_cash_at_close NUMERIC(12, 2),
    counted_cash_at_close NUMERIC(12, 2),
    difference_at_close NUMERIC(12, 2),
    closing_notes VARCHAR(250),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cash_register_opening_amount CHECK (opening_amount >= 0),
    CONSTRAINT ck_cash_register_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_cash_register_close_data CHECK (
        (status = 'OPEN'
            AND closed_by_user_id IS NULL
            AND closed_at IS NULL
            AND expected_cash_at_close IS NULL
            AND counted_cash_at_close IS NULL
            AND difference_at_close IS NULL)
        OR (status = 'CLOSED'
            AND closed_by_user_id IS NOT NULL
            AND closed_at IS NOT NULL
            AND expected_cash_at_close IS NOT NULL
            AND counted_cash_at_close IS NOT NULL
            AND counted_cash_at_close >= 0
            AND difference_at_close IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_cash_register_open_branch
    ON cash_register_sessions (branch_id)
    WHERE status = 'OPEN';

CREATE INDEX idx_cash_register_branch_opened
    ON cash_register_sessions (branch_id, opened_at DESC);

CREATE TABLE cash_register_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id UUID NOT NULL,
    session_id BIGINT NOT NULL REFERENCES cash_register_sessions (id),
    movement_type VARCHAR(20) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    concept VARCHAR(160) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    recorded_by_user_id BIGINT NOT NULL REFERENCES app_users (id),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    voided_by_user_id BIGINT REFERENCES app_users (id),
    voided_at TIMESTAMPTZ,
    void_reason VARCHAR(250),
    CONSTRAINT uk_cash_register_movement_operation UNIQUE (operation_id),
    CONSTRAINT ck_cash_register_movement_type
        CHECK (movement_type IN ('CASH_IN', 'CASH_OUT')),
    CONSTRAINT ck_cash_register_movement_amount CHECK (amount > 0),
    CONSTRAINT ck_cash_register_movement_concept CHECK (LENGTH(TRIM(concept)) > 0),
    CONSTRAINT ck_cash_register_movement_status CHECK (status IN ('ACTIVE', 'VOIDED')),
    CONSTRAINT ck_cash_register_movement_void CHECK (
        (status = 'ACTIVE'
            AND voided_by_user_id IS NULL
            AND voided_at IS NULL
            AND void_reason IS NULL)
        OR (status = 'VOIDED'
            AND voided_by_user_id IS NOT NULL
            AND voided_at IS NOT NULL
            AND void_reason IS NOT NULL)
    )
);

CREATE INDEX idx_cash_register_movements_session_recorded
    ON cash_register_movements (session_id, recorded_at, id);

ALTER TABLE order_payments
    ADD COLUMN cash_register_session_id BIGINT
        REFERENCES cash_register_sessions (id);

CREATE INDEX idx_order_payments_cash_register
    ON order_payments (cash_register_session_id, status, method);
